name: Deploy to VM

on:
  push:
    branches:
      - develop  # ajuste para a branch que deseja fazer o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest  # ou outro sistema operacional suportado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  # ou yarn install, dependendo do gerenciador de pacotes

    - name: Build
      run: npm run build  # ajuste para o comando de build da sua aplicaçãodh

    - name: Deploy to VM
      run: |
        ssh alexandre@34.106.31.160 'cd /home/apps/back && git pull && npm install && npm run build && pm2 restart your-app'
      env:
        SSH_PRIVATE_KEY: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDT/k7Ey25Yfpf9j4UQzkeOAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQDWH2kcGyRWyn93+j0wS5704Z/bk4KQ+sPk3Uy47ReJZLcZji/ZQV8Np88QiT81oyadN2mYopHbHCFEoiIqRaaqt/ei01yCpcP4RZAl3f7KGhofxJxPZZKdfDqKpTnDHp0ChSAZ8TEwih4Nu1y7uv+OEekKtaD8Z3YSLVYl91TpNJR8S0w1pvQj8ke4Wa5Bbp8RGNVT1LpC5pbWaSbmwKN3lG+WubsTiMF5RGcPLg/rjyeIGKO6vhteWp+l1zohKfCK3IsuLwGnShZUtBqk6z+EFOg8f2/4sjHvLMgRYDjbZMxyHF+qRSC994BPr9wRTZIMyq2IKKMTeBS32fixigHChgTuVDkmc2eLKSBQ5CXigD70TQ6/ee9p6Yx/f0gIRCjCyFkolbOmFYs5hHptkABWpF8cc5Yu/zCFCwpxxeKOiInurr5FJFUhPSHDfrjDYgYQkpOdlL2DAwEj6DN67tAvjhu/2aPkZ9BTt9bXiph3W5x/ldDtxTi4/C5YRSBE+j0AAAWQsrzTdiHAfCBfkoEAm0WDxdBRLI1hi8JS+1AdL9F9bQrwkNqiMrmq7ZwELsLiYqITVq16QTFoexDpKmqo7HnpNmJc11lPmh2d56+AgFIz4fnzV/iiMQRzg1EBud/H+K/WejVxqJLna5x8ckJeAzloPG/BI5Zf8isEoDH0RaIW5V/VY22q3Za84CvEAORYvQa9z38BmMrRYpFcGCfiKDITuadZ+a0Q3i0sAAlCEe8FbQZokHw4oD2IW6q0WJK5em+vnKStCB+Mvd2e/oI5mSS9nl1LuTp12x93jod/7EFZ7FpQrmwe3+k//dUpQQjlMvZYw0+HkjkN1dI/28EFDsUv+++pVrgtdkDjL9PSoda00rB5xHAzSOqQwDMFaaIizyXnVPIphWjqbcI90WeTYzIP7Pii5cGM2pwHSbF+l7tM2L7QAdrPzhstwNeReOCbYDYtAzKLGxGrNf3pu54j2QSsHtXowHsB6C+Niz6BNEts/fM4OeyYOMWxhZZxYPLjnz6s7pCkc5FuUUWZy62265QIG2ByWDLPYFd0eIFWMzBClcAezJnO9NfvNn324xPi3LGurPt8C05ffBcPtn/dUbc+Qv7ctLwTHZY61uGBefAZiO1HTjh6BXA1V+8s/qz4Qi4kXTCyhzg8XnYuzc+1/rmo/vRo0Aol4igP8ks1IRN4E+Mn3hmaRryf2b0+Zp95BxV/x3lHPfKNUIWRV7KlZIyJtDfys/7RmGTjrF18uRXTsGDRoFiAs0nqS2FIOp6R55/X+xgBJCsgwpaWjS/RUn7BWffqNNYovFsSEfckmSpy3ztjV/emF9sIX58GbapuPL/8cZTaLwbuUTA6t+zp+cnk0DZpEJX2Nf6xmzDy1pFAaaEPaGbjjX4hW909p+YixirqsYBpKFC27j9b3/ZfYLV/c5V0lYGRRaJ5z2GwXatO/0KGIWBx15xjxVvhc2ExcDSSKtGea75nu++C1oNyJMGd9jSBi0d8tIuBSSIbZiS8HOCzgyCicsNbONT5kFyFUUVLpKMInLHY70uB81GeV7gVIiwsUrKjtKMhEFP5ha5vpwMDmi885Mqi9/fI9aGtGDi5NRjx8gTkzETGmP9r+yNaa89+kW4xCB88n5grDN6g9vc0bZQyg4KjosxR5gPR5ExIJ9SqkIClsnVNXzRyEVvIuFb/Hn+A7TBwjJxP+JTirVjbNJwB3bELTHLXyNzXOOYkfJEKWotQs+oXEyES0KI1SmsU4iduPtjbmh7NtQAdfBo8xRbKqXBvKyo0S8XuvbS5FXecppP5tjP9DrZi+qLz9NifeXD0qWenCqJPOYHHslujlIZU9q8rOSKG1l/LPw1WndY7SlepeBBxIgVkEyt8E2X8/o4ShER/a+BOeXVbXUQCbxVmtWAWz/q3Wwo/ol0FCg0iICM9SPqi9ujL0/dH9USaEhC9XBpwEkgXj6C7khLMcAMNV1phtLzTg7WtwZxfEGadrp/cKxXdgtZnvioNFC3lyf3h9rD+VUyJtSouGp+e5qv7JHI+unliTixDfiGLreLaLg5C8u5paV7L6GptuABPp8gzpQaYD/h6m0DsLUemYQ9fu/FIkEZvn65T59GPUVOguuGu4d0r7EtlVrDVFl+0TzX+FavL0z8G6pogZGbLn/5XyM7O4U+6rHRPrNxFpSSuSUVWuSqvBCAJQNAE4N8VE3pSJBHClGWf/Ei4oXXN5Io+GcMoH29nT1/AVn1+iWe7cD7XLHYuMGXrhouVomlowFjmjqMX95eyY0UrgY6ARF4ErXqG0rlkf7nXQIBG89hwRvjajU9X0a6mV5x3wYf3YtjmiTThPUlOwMkt9LN6PkDRPu8WGm1siO8hCnr1jhOl9W4DPPnm0R49dT8+g41cTNHGH9g1hOZfKJmXbLw=
  # substitua pelo nome correto da variável secreta
