# This is a basic workflow to help you get started with Actions

name: Deploy to VM

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    
    - name: Install dependencies for build
      run: sudo npm install

    - name: Build
      run: sudo npm run build
      
    - name: Stop pm2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          sudo pm2 stop dev-management

    - name: Copy build to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        source: "./dist/*"
        target: /home/apps/back/an-management
    
    - name: Install dependencies for run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/apps/back/an-management/dist 
          sudo pnpm install

    - name: Execute prisma
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/apps/back/an-management/dist
          sudo pnpm prisma generate

    - name: Execute start script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/apps/back/an-management/dist
          sudo pm2 restart dev-management

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEPLOYS }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'O projeto {{ EVENT_PAYLOAD.repository.full_name }} - DEV foi implementado com sucesso na VPS.'

        # sudo git checkout develop
        # sudo git pull origin develop
        # sudo git status
        # sudo pnpm i
        # sudo pnpm build
